### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by etiennerunge** [ValentinGeorgesDubost/Doc-Lodel#1]
Hello Valentin,

Merci pour votre travail de documentation du logiciel.
Nous envisageons d'utiliser Lodel. La documentation que vous avez écrite est elle toujours d'actualité ? Elle est assez récente et je vois des notes de releases jusqu'à Lodel 1. 

Pourquoi cette documentation n'a t-ell pas été ajoutée au dépot officiel (OpenEdition) ?

Merci !

**Comment by PatGendre** [comment]
bonjour
merci de votre question. Je réponds pour Valentin qui était en stage chez OpenEdition en décembre dernier. L'objectif est de reprendre l'organisation de la doc Lodel actuellement répartie sur 3 sites (lodel.org, wiki github, lodel.hypotheses.org), afin de fournir la même info sous une forme plus homogène. Nous n'avons pas migré vers cette nouvelle doc readthedocs par manque de temps à y consacrer mais c'est toujours envisagé...
Cordialement
Patrick Gendre, OpenEdition

**Comment by etiennerunge** [comment]
Bonjour @PatGendre, 

Merci pour votre réponse rapide. 
Futur utilisateur de Lodel 1, il est agréable de trouver un support réactif.
Il se peut que dans les mois à venir j'ai quelques questions. Je posterai alors directement sur OpenEdition/Lodel
Merci,
Cordialement,
Étienne R.
